import PostsLists from "@/components/PostsLists";
import { allPosts, Post } from "contentlayer/generated";

const posts: Post[] = allPosts.sort((a, b) => b.date.localeCompare(a.date));

const totalPosts = posts.length;
const postsPerPage = 2;
const totalPages = Math.ceil(totalPosts / postsPerPage);

export const metadata = {
    title: "Lista de todos los posts",
    description: "Description posts - Generated by create next app",
  };

const Posts = () => {
    return <>
        <div>
            <h1 className="text-center my-4 text-3xl">Posts</h1>
            <div className="grid gap-4">
                <PostsLists posts={posts} />
            </div>
        </div>
    </>
};

export default Posts;
